### ISSUE TITLE
removeExperiments will delete all results no matter what ids are passed

### ISSUE THREAD

**Issue by ja-thomas** [mllg/batchtools#26] opened 2016-07-08 09:09 UTC
This was found by one of our master students.

Here is a smallish example:

```
library(batchtools)


reg <- makeExperimentRegistry(file.dir = "test_registry")

subsample <- function(data, job) {
  n <- nrow(data)
  train <- sample(n, floor(n * 0.5))
  test <- setdiff(seq(n), train)
  list(test = test, train = train)
}
data("iris", package = "datasets")
addProblem(reg, name = "iris", data = iris, fun = subsample, seed = 123)


forest.wrapper <- function(job, data, instance, ...) {
  library("randomForest")
  mod <- randomForest(Species ~ ., data = data,
                      subset = instance$train, ...)
  pred <- predict(mod, newdata = data[instance$test, ])
  table(data$Species[instance$test], pred)
  }
addAlgorithm(reg = reg, name = "forest", fun = forest.wrapper)


minsplit <- c(5, 10, 20, 6)
cp <- c(0.01, 0.1, 0.01, 0.1)
ntree <- c(100, 500, 1000, 200)

design <- data.frame(minsplit = minsplit, cp = cp, ntree = ntree)

algodes <- list( forest = design)
addExperiments(reg = reg, algo.design = algodes, repls = 2)
summarizeExperiments(reg = reg)

submitJobs()
getStatus()

all_jobs <- getJobPars(reg = reg)
jobs_500 <- subset(all_jobs, all_jobs$ntree == 500)
res_1 <- reduceResults(reg = reg, ids = jobs_500$job.id, fun = function(x, y) c(x, y))
res_1

removeExperiments(ids = jobs_500$job.id)

res_2 <- reduceResults(reg = reg, fun = function(x, y) c(x, y))

```

[Same results if we use the data.table]

Also, if we specify no ids in `removeExperiments` the documentation says that no jobs are deleted. But it seems that all results are deleted as well.

**Comment by mllg** [comment] 2016-07-08 14:32
Duplicate of https://github.com/mllg/batchtools/issues/21. Has already been fixed.

**Closed by mllg** 2016-07-08 14:32 UTC
