### ISSUE TITLE
flowchart and pkgdown

### ISSUE THREAD

**Issue by maelle** [mllg/batchtools#64] opened 2017-01-03 10:23 UTC
You have probably noticed this, the flowchart looks a bit weird (well only too big I guess) on the website:

![flowchart](https://cloud.githubusercontent.com/assets/8360597/21605075/041fa332-d1a7-11e6-887e-110730480a28.png)

**Comment by mllg** [comment] 2017-01-03 13:44
I currently see no good way to dynamically resize the figure to match the screen width. I've now replaced the svg with a png which looks okay-ish on devices with a high resolution. I'll leave this one open, maybe something comes to my mind later.

**Comment by jakobbossek** [comment] 2017-04-25 18:17
The problem is the fixed with attribute of the img tag in the HTML.
```html
<img src="tikz_prob_algo_simple.png" width="1019">
```
Setting `width="100%` does the job. However, I have no idea whether `knitr::include_graphics("tikz_prob_algo_simple.png")` accepts a percentage for the with argument.

**Comment by mllg** [comment] 2017-08-17 18:02
Works now for some reasons :+1:

**Closed by mllg** 2017-08-17 18:02 UTC
Labels: enhancement
